<script lang="ts" setup>
import { assert, keyByToMap } from "@acdh-oeaw/lib";
import * as turf from "@turf/turf";
import type { Feature } from "geojson";
import type { MapGeoJSONFeature } from "maplibre-gl";
import * as v from "valibot";

import type { SearchFormData } from "@/components/search-form.vue";
import type { EntityFeature } from "@/composables/use-create-entity";
import { categories, operatorMap } from "@/composables/use-get-search-results";
import type { GeoJsonFeature } from "@/utils/create-geojson-feature";

import { project } from "../config/project.config";

const router = useRouter();
const route = useRoute();
const t = useTranslations();

const { getUnprefixedId } = useIdPrefix();

const searchFiltersSchema = v.object({
	category: v.fallback(v.picklist(categories), "entityName"),
	search: v.fallback(v.string(), ""),
});

const entitySelectionSchema = v.object({
	selection: v.fallback(v.array(v.string()), []),
});

const searchFilters = computed(() => {
	return v.parse(searchFiltersSchema, route.query);
});

type EntitySelection = v.InferOutput<typeof entitySelectionSchema>;

type SearchFilters = v.InferOutput<typeof searchFiltersSchema>;

function setEntitySelection(query: Partial<EntitySelection>) {
	void router.push({ query: { mode: route.query.mode, ...query } });
}

function onChangeEntitySelection(values: EntityFeature) {
	const temp: EntitySelection = {
		selection: [getUnprefixedId(values["@id"])],
	};
	setEntitySelection(temp);
}

function setSearchFilters(query: Partial<SearchFilters>) {
	void router.push({ query: { mode: route.query.mode, ...query } });
}

function onChangeSearchFilters(values: SearchFormData) {
	setSearchFilters(values);
}

onMounted(() => {
	setMovementId({ id: selection.value as unknown as string });
});

const { data, isPending, isPlaceholderData } = useGetSearchResults(
	// @ts-expect-error Includes custom, per-instance system classes.
	computed(() => {
		const { search, category, ...params } = searchFilters.value;

		const operator = operatorMap[category];

		return {
			...params,
			search:
				search.length > 0
					? [{ [category]: [{ operator: operator, values: [search], logicalOperator: "and" }] }]
					: [],
			show: ["geometry", "when", "relations"],
			centroid: true,
			relation_type: ["P26", "P27"],
			system_classes: project.map.mapDisplayedSystemClasses,
			view_classes: ["event"],
			limit: 0,
		};
	}),
);

const isLoading = computed(() => {
	return isPending.value || isPlaceholderData.value;
});

const entities = computed(() => {
	return (
		data.value?.results.flatMap((result) => {
			return result.features;
		}) ?? []
	);
});

const entitiesById = computed(() => {
	return keyByToMap(entities.value, (entity) => {
		return entity.properties._id;
	});
});

let show = ref(false);
let showMovements = ref(false);

const movementId = ref<number | null>(null);

function togglePolygons() {
	show.value = !show.value;
}

function toggleMovements() {
	showMovements.value = !showMovements.value;
}

const selection = computed(() => {
	return route.query.selection;
});

const mode = computed(() => {
	return route.query.mode;
});
/**
 * Reduce size of geojson payload, which has an impact on performance,
 * because `maplibre-gl` will serialize geojson features when sending them to the webworker.
 */
const features = computed(() => {
	return entities.value
		.filter((entity) => {
			return entity.geometry;
		})
		.map((entity) => {
			return createGeoJsonFeature(entity);
		});
});

const movements = computed(() => {
	const move = entities.value
		.filter((move) => {
			return move.systemClass === "move";
		})
		.filter((feature) => {
			return feature.geometry && "geometries" in feature.geometry;
		})
		.map((feature) => {
			assert(feature.geometry, "Feature has no geometry");
			assert("geometries" in feature.geometry, "Feature has no geometries");
			const filteredGeometries = feature.geometry.geometries.filter((geo) => {
				return (
					geo.type === "Point" &&
					geo.shapeType === "centerpoint" &&
					!geo.title?.includes("(autogenerated)")
				);
			});

			const from = feature.relations?.find((rel) => {
				return rel.relationType?.startsWith("crm:P27");
			});

			const to = feature.relations?.find((rel) => {
				return rel.relationType?.startsWith("crm:P26");
			});

			const fromGeometry = filteredGeometries.find((geo) => {
				return geo.locationId && from?.relationTo?.endsWith(geo.locationId);
			});

			const toGeometry = filteredGeometries.find((geo) => {
				return geo.locationId && to?.relationTo?.endsWith(geo.locationId);
			});

			let featureClone = {
				...feature,
				geometry: {
					...feature.geometry,
					geometries: [fromGeometry, toGeometry].filter((move) => {
						return move != null;
					}),
				},
			};

			return featureClone;
		})
		.filter((move) => {
			return move.geometry.geometries.length === 2;
		});

	move.forEach((move) => {
		assert(move.geometry.geometries);
	});

	return move.map((entity) => {
		let feature = createGeoJsonFeature(entity);

		return feature;
	});
});

const events = computed(() => {
	const event = entities.value
		.filter((event) => {
			return event.viewClass === "event" && event.systemClass !== "move";
		})
		.filter((feature) => {
			return feature.geometry && "geometries" in feature.geometry;
		})
		.map((feature) => {
			assert(feature.geometry, "Feature has no geometry");
			assert("geometries" in feature.geometry, "Feature has no geometries");
			let featureClone = {
				...feature,
				geometry: {
					...feature.geometry,
					geometries: feature.geometry.geometries.filter((geo) => {
						return (
							geo.type === "Point" &&
							geo.shapeType === "centerpoint" &&
							!geo.title?.includes("(autogenerated)")
						);
					}),
				},
			};
			return featureClone;
		});

	return event.map((entity) => {
		let feature = createGeoJsonFeature(entity);
		return feature;
	});
});

const centerpoints = computed(() => {
	return features.value.filter((centerpoint) => {
		return centerpoint.geometry.type === "GeometryCollection";
	});
});

const points = computed(() => {
	return features.value.filter((point) => {
		return point.geometry.type === "Point";
	});
});

const popover = ref<{ coordinates: [number, number]; entities: Array<EntityFeature> } | null>(null);

interface onLayerClickParams {
	features: Array<MapGeoJSONFeature & Pick<GeoJsonFeature, "properties">>;
	targetCoordinates?: Array<[number, number]> | [number, number];
}

function onLayerClick({ features, targetCoordinates }: onLayerClickParams) {
	const entitiesMap = new Map<string, EntityFeature>();

	features.forEach((feature) => {
		const entity = entitiesById.value.get(feature.properties._id);
		if (entity != null) {
			entitiesMap.set(feature.properties._id, entity);
		}
	});

	const entities = Array.from(entitiesMap.values()).filter((e) => {
		return e.geometry != null;
	});

	let coordinates = null;

	if (targetCoordinates != null) {
		if (typeof targetCoordinates[0] === "number" && typeof targetCoordinates[1] === "number") {
			coordinates = targetCoordinates as [number, number];
		} else {
			coordinates = turf.center(turf.points(targetCoordinates as Array<[number, number]>)).geometry
				.coordinates as [number, number];
		}
	} else {
		for (const entity of entities) {
			if (entity.geometry?.type === "GeometryCollection") {
				coordinates = entity.geometry.geometries.find((g) => {
					return g.type === "Point";
				})?.coordinates as [number, number] | undefined;

				if (coordinates != null) break;
			}
		}
	}

	popover.value = {
		coordinates:
			coordinates ??
			(turf.center(createFeatureCollection(entities as Array<Feature>)).geometry.coordinates as [
				number,
				number,
			]),
		entities,
	};
	console.log("Popup: ", popover.value);
}

watch(data, () => {
	/**
	 * Close popover when search results change, to avoid displaying popup for features which are
	 * no longer in the search results set.
	 */
	popover.value = null;
});

const selectionCoordinates = ref<[number, number] | undefined>(undefined);
const selectionBounds = ref<Array<[number, number]> | undefined>(undefined);

function setCoordinates(entity: EntityFeature, coordinates: Ref<[number, number] | undefined>) {
	if (entity.geometry?.type === "GeometryCollection") {
		if (entity.systemClass === "move") {
			const selectedMove = movements.value.find((move) => {
				return move.properties._id === entity.properties._id;
			});
			if (selectedMove?.geometry && "geometries" in selectedMove.geometry) {
				selectionBounds.value = selectedMove.geometry.geometries.map((geo) => {
					assert("coordinates" in geo);
					return geo.coordinates as [number, number];
				});
				assert(selectionBounds.value);

				const points = turf.points(selectionBounds.value);
				coordinates.value = turf.center(points).geometry.coordinates as [number, number];

				return;
			}
		}
		coordinates.value = entity.geometry.geometries.find((g) => {
			return g.type === "Point";
		})?.coordinates as [number, number] | undefined;
		selectionBounds.value = undefined;
	}

	if (entity.geometry?.type === "Point") {
		coordinates.value = entity.geometry.coordinates as unknown as [number, number];
		selectionBounds.value = undefined;
	}
}

watchEffect(() => {
	if (mode.value && selection.value) {
		const entity = entities.value.find((feature) => {
			const id = getUnprefixedId(feature["@id"]);
			return id === selection.value;
		});

		if (entity) {
			setCoordinates(entity, selectionCoordinates);

			if (entity.geometry == null) return;
			popover.value = {
				coordinates:
					selectionCoordinates.value ??
					(turf.center(createFeatureCollection([entity as Feature])).geometry.coordinates as [
						number,
						number,
					]),
				entities: [entity],
			};
		}
	}
});

watch(
	() => {
		return selection.value;
	},
	() => {
		setMovementId({ id: selection.value as unknown as string });
	},
);

const movementDetails = computed(() => {
	if (multipleMovements.data.value) {
		return multipleMovements.data.value;
	} else return null;
});

const linkedMovements = computed(() => {
	if (movementDetails.value === null) {
		return null;
	}

	const features = Object.values(movementDetails.value).flatMap((entity) => {
		if (entity && typeof entity === "object" && Array.isArray(entity.features)) {
			return entity.features as Array<EntityFeature>;
		}
		return [];
	});

	// Now map through the features to get the IDs
	return features.map((movement) => {
		return {
			id: getUnprefixedId(movement["@id"]),
			systemClass: movement.systemClass,
		};
	});
});

const multipleMovements = useGetLinkedEntitiesRecursive(
	computed(() => {
		return { entityId: movementId.value };
	}),
);

function setMovementId({ id }: { id: string | null }) {
	return (movementId.value = id ? parseInt(id) : null);
}
</script>

<template>
	<div :class="project.fullscreen ? 'relative grid' : 'relative grid grid-rows-[auto_1fr] gap-4'">
		<div
			:class="
				project.fullscreen ? 'absolute z-10 flex w-full justify-center pointer-events-none' : ''
			"
		>
			<SearchForm
				:class="
					project.fullscreen
						? 'bg-white/90 dark:bg-neutral-900 max-w-[800px] w-full mt-2 rounded-md p-6 shadow-md pointer-events-auto'
						: ''
				"
				:category="searchFilters.category"
				:search="searchFilters.search"
				@submit="onChangeSearchFilters"
			/>
		</div>

		<VisualisationContainer
			v-slot="{ height, width }"
			class="border"
			:class="{ 'opacity-50 grayscale': isLoading }"
		>
			<div class="absolute bottom-0 z-10 mb-2 flex w-full justify-center">
				<div
					class="max-h-72 gap-2 overflow-y-auto overflow-x-hidden rounded-md border-2 border-transparent bg-white/90 p-2 text-sm font-medium shadow-md dark:bg-neutral-900"
				>
					<div class="grid grid-cols-[auto_auto_auto_auto_1fr] items-center gap-3 align-middle">
						<div class="grid grid-cols-[auto_1fr] gap-1">
							<span
								class="m-1.5 size-2 rounded-full"
								:style="`background-color: ${project.colors.geojsonPoints}`"
							></span>
							{{ $t("DataMapView.point") }} ({{ points.length }})
						</div>
						<div class="grid grid-cols-[auto_1fr] gap-1">
							<span
								class="m-1.5 size-2 rounded-full"
								:style="`background-color: ${project.colors.geojsonAreaCenterPoints}`"
							></span>
							{{ $t("DataMapView.centerpoint") }} ({{ centerpoints.length }})
						</div>
						<div class="grid grid-cols-[auto_1fr] gap-1">
							<span
								class="m-1.5 size-2 rounded-full"
								:style="`background-color: ${project.colors.geojsonMovement}`"
							></span>
							{{ $t("DataMapView.movement") }} ({{ movements.length }})
						</div>
						<div>
							<Toggle variant="iiif" @click="togglePolygons">
								{{ $t("DataMapView.polygon") }}
							</Toggle>
						</div>
						<div>
							<Toggle variant="iiif" @click="toggleMovements">
								{{ $t("DataMapView.showMovement") }}
							</Toggle>
						</div>
					</div>
				</div>
			</div>

			<GeoMap
				v-if="height && width"
				:features="features"
				:movements="movements"
				:events="events"
				:height="height"
				:width="width"
				:has-polygons="show"
				:show-movements="showMovements"
				:multiple-movements="linkedMovements"
				:current-selection-coordinates="selectionCoordinates"
				:selection-bounds="selectionBounds"
				:current-selection-id="String(selection)"
				@layer-click="onLayerClick"
				@movement-hovered="setMovementId"
			>
				<GeoMapPopup
					v-if="popover != null"
					:coordinates="popover.coordinates"
					@close="popover = null"
				>
					<article
						v-for="entity of popover.entities"
						:key="entity.properties._id"
						class="grid gap-1 font-body text-xs"
					>
						<strong class="font-medium">
							<NavLink
								href="#"
								class="flex cursor-pointer items-center gap-1 underline decoration-dotted hover:no-underline"
								@click="onChangeEntitySelection(entity)"
							>
								<Component :is="getEntityIcon(entity.systemClass)" class="size-3.5 shrink-0" />
								{{ entity.properties.title }}
							</NavLink>
						</strong>
						<dl
							v-if="entity.when?.timespans != null && entity.when.timespans.length > 0"
							class="grid grid-cols-[auto_auto] justify-start gap-x-6 gap-y-1 pl-[18px] text-2xs text-neutral-600"
						>
							<template v-for="(timespan, index) of entity.when.timespans" :key="index">
								<template v-if="timespan.start?.earliest != null || timespan.start?.latest != null">
									<div class="grid gap-0.5">
										<dt class="font-medium uppercase">{{ t("DataMapView.start-date") }}</dt>
										<dd>{{ createDateSpan(timespan.start) }}</dd>
									</div>
								</template>
								<template v-if="timespan.end?.earliest != null || timespan.end?.latest != null">
									<div class="grid gap-0.5">
										<dt class="font-medium uppercase">{{ t("DataMapView.end-date") }}</dt>
										<dd>{{ createDateSpan(timespan.end) }}</dd>
									</div>
								</template>
							</template>
						</dl>
					</article>
				</GeoMapPopup>
			</GeoMap>

			<Centered v-if="isLoading" class="pointer-events-none">
				<LoadingIndicator class="text-neutral-950" size="lg" />
			</Centered>
		</VisualisationContainer>
	</div>
</template>
